<?php
namespace example;


class ExampleConst
{
    const TOKEN = "V4uhpflEafFdo_0HNCEKKtYhcLhSfm9yIvfpgppsFS4ZlUwzeI4RgEBXbAqRz2oInqRxyL5GPtj6e9nhb5iJXJUzs-eNpT3zBWGMZuA5DuLiaLTJnoiQFxDsgdZmuKOSOFh30el25N_esTTPc8umkqGIN0YPAtgg9J4kY4vWufnU4CUG2F52FX_-UPGNAMQdDIjyZoS5bcAzTuuKlhluQgH_mwDcTSkLYP-RS2hrzS0";

}